export enum ACTIONS {
  ADD_PROJECT = 'ADD_PROJECT',
  REMOVE_PROJECT = 'REMOVE_PROJECT',
  REMOVE_TASK = 'REMOVE_TASK',
  ADD_TASK = 'ADD_TASK',
  UPDATE_TASK = 'UPDATE_TASK',
  DRAG_DROP = 'DRAG_DROP',
}
